/*
 * Licence Studio l'Equipe.
 */
package com.phenix.swing;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import java.awt.Toolkit;
import java.awt.Window;
import java.net.URL;
import javax.swing.JDialog;

/**
 * Fenêtre indiquant un message.<br>
 * Cette fenêtre ne peut pas être modal car il doit pouvoir se passer des choses
 * pendant quelle est affichée.
 *
 * @author <a href="mailto:edouard128@hotmail.com">Edouard Jeanjean</a>
 */
public final class FenetreMessage extends JDialog {

    /**
     * Crée la fenêtre.
     *
     * @param parent La fenêtre parente.
     * @param message Le message à afficher.
     */
    public FenetreMessage(@Null Window parent, @NotNull String message) {
        this(parent, message, null);
    }

    /**
     * Crée la fenêtre.
     *
     * @param parent La fenêtre parente.
     * @param message Le message à afficher.
     * @param image URL de l'image à utiliser.
     */
    public FenetreMessage(@Null Window parent, @NotNull String message, @Null URL image) {
        super(parent);
        initComponents();

        this.L_message.setText(message);

        // Ajoute une icone à l'application.
        if (image != null) {
            setIconImage(Toolkit.getDefaultToolkit().getImage(image));
        }

        JPositionMultiScreen.setLocation(this, parent);
    }

    /**
     * Modifie le message.
     *
     * @param message Le message.
     */
    private void setMessage(@NotNull String message) {
        this.L_message.setText(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Information");

        L_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(L_message, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_message;
    // End of variables declaration//GEN-END:variables
}
